FROM ubuntu:latest

LABEL name="ubuntu-ts"

# ❗ Do not store secrets in Dockerfile (use environment injection at runtime)
# ENV AWS_ACCESS_KEY_ID=...
# ENV AWS_SECRET_ACCESS_KEY=...
# ENV AWS_DEFAULT_REGION=us-east-1

ARG T_VERSION="1.11.0"
ARG P_VERSION="1.12.0"

# Install basic tools
RUN apt update && \
    apt install -y jq net-tools curl wget unzip nginx iputils-ping

# Set working directory
WORKDIR /tmp

# Download, unzip, install Terraform & Packer
RUN wget -O terraform.zip https://releases.hashicorp.com/terraform/${T_VERSION}/terraform_${T_VERSION}_linux_amd64.zip && \
    wget -O packer.zip https://releases.hashicorp.com/packer/${P_VERSION}/packer_${P_VERSION}_linux_amd64.zip && \
    unzip -o terraform.zip && \
    unzip -o packer.zip && \
    chmod +x terraform packer && \
    mv terraform /usr/local/bin/ && \
    mv packer /usr/local/bin/ && \
    terraform version && packer version

# Run Nginx in foreground
CMD ["nginx", "-g", "daemon off;"]
